name: Snapshot Release

on:
  workflow_dispatch:

jobs:
  snapshot:
    name: Snapshot Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.11.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build package
        run: pnpm run build

      - name: Run type checking
        run: pnpm run typecheck

      - name: Run linting
        run: pnpm run lint

      - name: Create Snapshot Release
        run: |
          npm run version-packages --snapshot "${{ github.ref_name }}"
          echo '---'
          echo 'Detected Changes:'
          git diff
          echo '---'
          npm run release --tag "${{ github.ref_name }}" --no-git-tag
